name: Build and Deploy UI WebApp

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    environment: default
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
          
      - name: Install deps
        run: npm ci
        
      - name: Build the app
        run: REACT_APP_AZ_ENTRA_APP_AUTHORITY=${{ vars.REACT_APP_AZ_ENTRA_APP_AUTHORITY }} REACT_APP_AZ_ENTRA_APP_ID=${{ vars.REACT_APP_AZ_ENTRA_APP_ID }} REACT_APP_AZ_ENTRA_APP_REDIRECT_URL=${{ vars.REACT_APP_AZ_ENTRA_APP_REDIRECT_URL }} REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }} npm run build
          
      - name: Deploy (only Main branch)
        if: ${{ github.ref == 'refs/heads/main' }}
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_MUSHROOM_047751F03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "build"
          skip_app_build: true # we only need deploy here
          output_location: "" 